import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medicare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col overflow-x-hidden bg-[#F8F8FF]">
          <header className="bg-white sticky top-0 left-0 w-full py-6 md:py-6 xl:py-4 px-6 md:px-10 lg:px-16 z-50">
            <Header />
          </header>

          <div className="flex-1 overflow-x-hidden">
            <main className="">
              {children}
            </main>
          </div>
      </body>
    </html>
  );
}
